main: me.samy.HelloWorld.Main
name: Multiplugin
version: 1.0
author: LilSamy
api-version: 1.15

commands:
  launch:
    aliases: [lch]
  Hello:
    aliases: [hi]
  Doctor:
    aliases: [doc]
  gods:
  startool:
  Skull:
  CreateNPC:
  Gamble:
  